kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ template "hpe-array-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "hpe-array-exporter.name" . }}
    chart: {{ template "hpe-array-exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  selector:
    matchLabels:
      app: hpe-array-exporter
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ template "hpe-array-exporter.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: array-exporter
          image: {{ .Values.image.registry }}/hpestorage/array-exporter:v1.0.0
          ports:
            - containerPort: 8080
          args:
            - "--telemetry.addr=:8080"
            - "--telemetry.path=/metrics"
            {{- if eq .Values.acceptEula true }}
            - "--accept-eula"
            {{- else }}
            {{- fail "\n\nERROR: The acceptEula value must be set to true to confirm acceptance.\n\n" }}
            {{- end }}
            {{- if .Values.metrics }}
            {{- if .Values.metrics.disableIntrospection }}
            - "--metrics.disable-introspection"
            {{- end }}
            {{- end }}
            - "/etc/config"
          env:
            - name: LOG_LEVEL
              value: {{ .Values.logLevel }}
          imagePullPolicy: {{ .Values.image.pullPolicy | quote }}
          volumeMounts:
            - name: storage-system-config
              mountPath: /etc/config
      volumes:
        - name: storage-system-config
          secret:
            secretName: {{ .Values.arraySecret | quote }}

---
{{- $service := .Values.service | default dict }}
kind: Service
apiVersion: v1
metadata:
  name: {{ template "hpe-array-exporter.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "hpe-array-exporter.name" . }}
    chart: {{ template "hpe-array-exporter.chart" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    {{- with $service.labels }}
{{ toYaml . | indent 4 }}
    {{- end }}
  annotations:
    {{- with $service.annotations }}
{{ toYaml . | indent 4 }}
    {{- end }}
spec:
  {{- $serviceType := $service.type | default "ClusterIP" }}
  type: {{ $serviceType | quote }}
  ports:
    - name: http-metrics
      port: {{ $service.port | default 9090 }}
      {{- if eq $serviceType "NodePort" }}
      {{- if $service.nodePort }}
      nodePort: {{ $service.nodePort }}
      {{- end }}
      {{- end }}
      protocol: TCP
      targetPort: 8080
  selector:
    app: {{ template "hpe-array-exporter.name" . }}
    release: {{ .Release.Name }}
    
# Source: hpe-array-exporter/templates/hpe-array-exporter.yaml
kind: ServiceMonitor
apiVersion: monitoring.coreos.com/v1
metadata:
  name: mdc-3par01-hpe-array-exporter-servicemonitor
  namespace: {{ .Release.Namespace }}
  labels:
    # A selector for this label is used by a Prometheus Operator
    # installed via OLM
    k8s-app: prometheus
    # A "release" label selector is used by the Helm Kube Prometheus Stack,
    # with the value as the release specified on chart installation
    release: prometheus
spec:
  # Match the namespace of the target Array Exporter service,
  # or omit the namespaceSelector
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  selector:
    matchLabels:
      app: hpe-array-exporter
  endpoints:
    - port: http-metrics
      scheme: http
      interval: 1m
  # Corresponding labels on the Array Exporter service are added to
  # the scraped metrics
  #targetLabels:
  #  - array

NOTES:
Use of this software is governed by the HPE End User License Agreement at
https://www.hpe.com/us/en/software/licensing.html.
    
